version: "3.9"

services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:22.02-py3
    volumes:
      - ./model_repository:/models
    command: tritonserver --model-repository=/models
    networks:
      - bot

  postgres-db:
    container_name: postgres-db
    image: postgres:13-alpine
    volumes:
      - tg-bot-data:/var/lib/postgresql/data/
    networks:
      - bot

  tg_bot:
    container_name: tg_bot
    build: .
    command: sh -c "(sleep 5) && python src/main.py"
    volumes:
      - .:/bot/
    networks:
      - bot
    depends_on:
      - postgres-db

volumes:
  tg-bot-data:

networks:
  bot:
    driver: bridge
