platform: "pytorch_libtorch"
max_batch_size: 8
input [
	{
		name: "INPUT__0"
		data_type: TYPE_FP32
		dims: [20, 20, 3]
	}
]
output [
	{
		name: "OUTPUT__0"
		data_type: TYPE_FP32
		dims: [5]
	}
]
version_policy: { all { }}
instance_group [
	{
		count: 2
		kind: KIND_CPU
	}
]
